name: Backup

on:
  workflow_dispatch:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  backup:
    name: Backup Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
      - name: Push to Backup Repository
        run: |
          git fetch --prune
      - name: List Local Branches
        run: |
          branches=$(git branch --format='%(refname:short)' --list)
          echo "$branches"  # 可以添加这个命令以查看获取到的分支列表
        shell: bash
      - name: Push to Backup Repository
        run: |
          git remote set-url --push origin https://github.com/BlankTMing/ManifestAutoUpdate_Backup
      - name: Push Local Branches to Remote
        run: |
          for branch in $branches; do
            git push origin $branch
          done
        shell: bash
  
      - name: Push to Backup Repository
        run: |
          for tag in $(git tag); do git push origin $tag; done
