name: Backup

on:
  workflow_dispatch:
jobs:
  backup:
    name: Backup Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Push All Branches to Remote Repository
        run: |
          git clone --mirror https://github.com/BlankTMing/ManifestAutoUpdate
          git remote set-url origin https://github.com/BlankTMing/ManifestAutoUpdate_Backup
          git push --mirror origin
