name: Backup

on:
  workflow_dispatch:
jobs:
  backup:
    name: Backup Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
      - name: Push All Branches to Remote Repository
        run: |
          git remote set-url --push origin https://github.com/BlankTMing/ManifestAutoUpdate_Backup
          run: git fetch --all
